sudo: true
language: node_js, python
before_install:
  - npm update -g npm
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update -q
  - sudo apt-get install -y rethinkdb --force-yes
  - sudo pip install -r requirements.pip
before_script:
  - npm install -g babel
  - npm install
  - rethinkdb --bind all --daemon
  - echo rethinkdb -v
  - python ./scraper -i -g -c -db caltrain_test
node_js:
  - 'iojs-v1.4.2'
python:
  - '2.7'
branches:
   only:
     - master
notifications:
  email: false
script: npm test
