server:
  image: iojs
  ports:
   - "80:8080"
  links:
   - "rethinkdb"
  environment:
    NODE_ENV: docker-local
    PORT: 8080
rethinkdb:
  image: dockerfile/rethinkdb
  ports:
   - "10001:8080"
   - "10002:28015"
   - "10003:29015"