rethinkdb:
  image: dockerfile/rethinkdb
  ports:
   - "10001:8080"
   - "10002:28015"
   - "10003:29015"
server:
  image: unlucio/iojs
  ports:
   - "80:8080"
  links:
   - "rethinkdb"
  environment:
    NODE_ENV: production
    PORT: 8080
  volumes:
    - ./:/app
  command: /bin/bash /app/server.sh