server:
  image: unlucio/iojs
  ports:
   - "10100:8080"
  environment:
    NODE_ENV: production
    RETHINKDB_HOST: rethinkdb.thejsj.com
    PORT: 8080
  volumes:
    - ./:/app
  command: /bin/bash /app/server.sh
