rethinkdb:
  image: dockerfile/rethinkdb
  ports:
   - "10101:8080"
   - "10102:28015"
   - "10103:29015"
server:
  image: unlucio/iojs
  ports:
   - "10100:8080"
  links:
   - "rethinkdb"
  environment:
    NODE_ENV: production
    PORT: 8080
  volumes:
    - ./:/app
  command: /bin/bash /app/server.sh